
import javax.swing.JOptionPane;
import java.sql.*;
import Dao.*;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author moluh
 */
public class ManageProducts extends javax.swing.JFrame {
    private int productPk = 0;
    private int totalQty = 0;

    /**
     * Creates new form ManageProducts
     */
    public ManageProducts() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void getAllCategory(){
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from category");
            comboBoxCat.removeAllItems();
            while(rs.next()){
                comboBoxCat.addItem(rs.getString("CategoryID")+"-"+rs.getString("CategoryName"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private boolean validateFields(String formType){
        if(formType.equals("edit") && !txtName.getText().equals("") && !jlabel5.getText().equals("")){
            return false;
        }
        else if(formType.equals("new") && !txtName.getText().equals("") && !jlabel5.getText().equals("") && !jLabel7.getText().equals("")){
            return false;
        }
        else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodTab = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jlabel5 = new javax.swing.JLabel();
        numP = new javax.swing.JTextField();
        lblQ = new javax.swing.JLabel();
        numQ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        comboBoxCat = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setText("Manage Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 6, -1, -1));

        prodTab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        prodTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "ProductName", "description", "brand", "Price", "Quantity", "BottleSize", "CategoryID", "CategoryName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        prodTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(prodTab);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 530));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 280, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Description");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel.setText("Brand");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        txtBrand.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 280, -1));

        jlabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel5.setText("Price");
        getContentPane().add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        numP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPActionPerformed(evt);
            }
        });
        getContentPane().add(numP, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 280, -1));

        lblQ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQ.setText("Quantity");
        getContentPane().add(lblQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        numQ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(numQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 280, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("BottleSize");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        txtSize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 280, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Category");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        txtDesc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 280, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, -1, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, -1, -1));

        comboBoxCat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboBoxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        comboBoxCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCatActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel4.setPreferredSize(new java.awt.Dimension(850, 600));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getAllCategory();
        
        DefaultTableModel model = (DefaultTableModel) prodTab.getModel();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from products inner join category on products.Category = category.CategoryID");
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("ProductID"), rs.getString("ProductName"), rs.getString("Description"), rs.getString("Brand"), rs.getString("Price"), rs.getString("Quantity"),rs.getString("BottleSize"),rs.getString("Category"),rs.getString(10)});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void numPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String ProductName = txtName.getText();
        String Description = txtDesc.getText();
        String Brand = txtBrand.getText();
        String Price = numP.getText();
        String Quantity = numQ.getText();
        String BottleSize = txtSize.getText();
        String Category = (String) comboBoxCat.getSelectedItem();
        String CategoryID[] = Category.split("-",0);
        if (validateFields("new")) {
            JOptionPane.showMessageDialog(null, "Fill all required fields!");
        } else {
            try {
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("INSERT INTO products(ProductName,Description,Brand,Price,Quantity,BottleSize,Category) VALUES(?,?,?,?,?,?,?)");
                ps.setString(1, ProductName);
                ps.setString(2, Description);
                ps.setString(3, Brand);
                ps.setString(4, Price);
                ps.setString(5, Quantity);
                ps.setString(6, BottleSize);
                ps.setString(7, CategoryID[0]);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Product recordeds succesfully");
                setVisible(false);
                new ManageProducts().setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String ProductName = txtName.getText();
        String Description = txtDesc.getText();
        String Brand = txtBrand.getText();
        String Price = numP.getText();
        String Quantity = numQ.getText();
        String BottleSize = txtSize.getText();
        String Category = (String) comboBoxCat.getSelectedItem();
        String CategoryID[] = Category.split("-",0);
        if (validateFields("edit")) {
            JOptionPane.showMessageDialog(null, "Fill all required fields!");
        } else {
            try {
                if(!Quantity.equals("")){
                    totalQty = totalQty + Integer.parseInt(Quantity);
                }
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("UPDATE products SET ProductName=?,Description=?,Brand=?,Price=?,Quantity=?,BottleSize=?,Category=? where ProductID=?");
                ps.setString(1, ProductName);
                ps.setString(2, Description);
                ps.setString(3, Brand);
                ps.setString(4, Price);
                ps.setInt(5, totalQty);
                ps.setString(6, BottleSize);
                ps.setString(7, CategoryID[0]);
                ps.setInt(8,productPk);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Product updated succesfully");
                setVisible(false);
                new ManageProducts().setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void prodTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodTabMouseClicked
        // TODO add your handling code here:
        int index = prodTab.getSelectedRow();
        TableModel model = prodTab.getModel();

        String ID = model.getValueAt(index, 0).toString();
        productPk = Integer.parseInt(ID);

        String Name = model.getValueAt(index, 1).toString();
        txtName.setText(Name);
        String Desc = model.getValueAt(index, 2).toString();
        txtDesc.setText(Desc);
        String Brand = model.getValueAt(index, 3).toString();
        txtBrand.setText(Brand);
        String Price = model.getValueAt(index, 4).toString();
        numP.setText(Price);
        String Qty = model.getValueAt(index, 5).toString();
        totalQty = 0;
        lblQ.setText("Add quantity");
        totalQty = Integer.parseInt(Qty);
        String size = model.getValueAt(index, 6).toString();
        txtSize.setText(size);
        comboBoxCat.removeAllItems();
        String category = model.getValueAt(index, 7).toString();
        String categoryName = model.getValueAt(index, 8).toString();
        comboBoxCat.addItem(category+"-"+categoryName);
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from category");
            while(rs.next()){
                if(Integer.parseInt(category) != rs.getInt(1))
                comboBoxCat.addItem(rs.getString("CategoryID")+"-"+rs.getString("CategoryName"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_prodTabMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int index = prodTab.getSelectedRow();
        TableModel model = prodTab.getModel();
        
        try {
                JOptionPane.showConfirmDialog(null, "Do you want to delete this product ?", "Select", JOptionPane.YES_NO_OPTION);
                Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("DELETE FROM products where ProductID=?");
                
                ps.setInt(1, productPk);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "product Deleted succesfully");
                setVisible(false);
                new ManageProducts().setVisible(true);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboBoxCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboBoxCat;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel lblQ;
    private javax.swing.JTextField numP;
    private javax.swing.JTextField numQ;
    private javax.swing.JTable prodTab;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
